package crdhn.usermanagement.entity;
// Generated Feb 7, 2017 3:19:26 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Permission generated by hbm2java
 */
@Entity
@Table(name="permission"
    ,catalog="user_management"
)
public class Permission  implements java.io.Serializable {


     private Integer idPermission;
     private int permission;
     private String name;
     private String description;
     private Set<PermissionUser> permissionUsers = new HashSet<PermissionUser>(0);

    public Permission() {
    }

	
    public Permission(int permission, String name) {
        this.permission = permission;
        this.name = name;
    }
    public Permission(int permission, String name, String description, Set<PermissionUser> permissionUsers) {
       this.permission = permission;
       this.name = name;
       this.description = description;
       this.permissionUsers = permissionUsers;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_permission", unique=true, nullable=false)
    public Integer getIdPermission() {
        return this.idPermission;
    }
    
    public void setIdPermission(Integer idPermission) {
        this.idPermission = idPermission;
    }

    
    @Column(name="permission", nullable=false)
    public int getPermission() {
        return this.permission;
    }
    
    public void setPermission(int permission) {
        this.permission = permission;
    }

    
    @Column(name="name", nullable=false, length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="permission")
    public Set<PermissionUser> getPermissionUsers() {
        return this.permissionUsers;
    }
    
    public void setPermissionUsers(Set<PermissionUser> permissionUsers) {
        this.permissionUsers = permissionUsers;
    }




}


