package crdhn.usermanagement.entity;
// Generated Feb 7, 2017 3:19:26 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PermissionUser generated by hbm2java
 */
@Entity
@Table(name="permission_user"
    ,catalog="user_management"
)
public class PermissionUser  implements java.io.Serializable {


     private Integer id;
     private Permission permission;
     private User user;

    public PermissionUser() {
    }

    public PermissionUser(Permission permission, User user) {
       this.permission = permission;
       this.user = user;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="id_permission", nullable=false)
    public Permission getPermission() {
        return this.permission;
    }
    
    public void setPermission(Permission permission) {
        this.permission = permission;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="id_user", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }




}


