/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package crdhn.queue.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum TQErrorCode implements org.apache.thrift.TEnum {
  QUEUE_OK(0),
  QUEUE_FAILED(1);

  private final int value;

  private TQErrorCode(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TQErrorCode findByValue(int value) { 
    switch (value) {
      case 0:
        return QUEUE_OK;
      case 1:
        return QUEUE_FAILED;
      default:
        return null;
    }
  }
}
